version: "3.8"
services:
  db:
    image: mysql:8.0.20
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: camprep_app
      MYSQL_PASSWORD: password
    ports:
      - 4306:3306
    volumes:
      - mysql-db:/var/lib/mysql
  api:
    tty: true
    stdin_open: true
    depends_on:
      - db
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec bin/rails server -b '0.0.0.0'"
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: yarn dev
    ports:
      - 8000:3000
volumes:
  node_modules:
    driver: local
  mysql-db:
    driver: local
